spring.application.name=emp-crud-backend
spring.datasource.url=jdbc:mysql://localhost:3306/db_5_aug?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Allow CORS for React frontend
server.port=8080
