spring.application.name=emp-crud-backend

# Use Environment Variables for Production (Render)
# Fallback to local values for development
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/db_5_aug?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server settings
server.port=${PORT:8085}

